### ISSUE TITLE
Can't build package

### ISSUE THREAD

**Issue by hamac** [ng2-ui/ng2-map#10]
Trying to fix issue #9, I could not get the project to build.

I tried:
- npm install
- npm run build

But I get the following errors:

ERROR in ./src/components/info-window.ts
(34,22): error TS2503: Cannot find namespace 'google'.
ERROR in ./src/components/info-window.ts
(35,19): error TS2503: Cannot find namespace 'google'.
ERROR in ./src/components/info-window.ts
(50,45): error TS2503: Cannot find namespace 'google'.
...
...

"npm run build:ts" works but "npm run build:umd" gives the previous errors

I am totally new to npm/webpack. Am I missing something?

Thanks

**Comment by allenhwkim** [comment]
I could not find a way to remove those error messages.
However it build umd.js properly, at least for me. node module `@typings/googlemaps` is supposed to fix that error, but it seems not. I do not want to introduce another `typings` on the top of node_modules.

**Comment by aitboudad** [comment]
fixed by #11

**Comment by hamac** [comment]
Yes, I can now build without errors.
Thanks guys!

**Comment by allenhwkim** [comment]
Added a file into tslint.json gave me no error
https://github.com/ng2-ui/ng2-map/blob/master/tsconfig.json#L24
