### ISSUE TITLE
high cpu usage when opening info window multiple times

### ISSUE THREAD

**Issue by soyersoyer** [ng2-ui/ng2-map#100]
When you open the info window multiple times, the browser uses more and more cpu.
https://plnkr.co/edit/UAspatwiHiz1gUX2nw9s?p=preview

I think it is related to the zone and the change detection.

**Comment by allenhwkim** [comment]
@soyersoyer thanks for reporting this, but can you provide a screenshot of it. I just tried and could not find what you found.

**Comment by soyersoyer** [comment]
Sorry.
Steps to reproduce:
1. open the plunker
2. click on the show random markers
3. click all of the markers to open info window 10 times in various positions
4. watch your browser's cpu usage

when you repeat the 2. and 3. steps 4-5 times, your browser's cpu usage will be 20-30% constantly.

**Comment by allenhwkim** [comment]
I have no solution at the moment. I may try infoWindow.close(), but I am not sure about it.

**Comment by soyersoyer** [comment]
This is a google maps api issue, so I am closing here.
https://code.google.com/p/gmaps-api-issues/issues/detail?id=10025
