### ISSUE TITLE
google not defined error in simple example

### ISSUE THREAD

**Issue by sauravMSFT** [ng2-ui/ng2-map#112]
google not defined when setting map options like 
```
options = {
    streetViewControl: false,
    zoomControlOptions: {
      position: google.maps.ControlPosition.TOP_RIGHT
    }
  }
```

Steps to reproduce and a minimal demo

  - _create a sample app_
  - _try to set option like zoomControlOptions or others which are from ```google namespace```

**Comment by allenhwkim** [comment]
google api is not downloaded when executes. Please include google api in ur index.html or do it with lazy loading.
