### ISSUE TITLE
TypeError: Cannot read property '__e3_' of undefined (DrawingManager)

### ISSUE THREAD

**Issue by IAMtheIAM** [ng2-ui/ng2-map#113]
The drawing manager produces the following error after creating any shape:
`TypeError: Cannot read property '__e3_' of undefined`

I cloned your repo, `npm i`, `npm build:app`, `npm start`
Navigate to DrawingManager page. Draw any shape, circle, polygon, square.
Error occurs when shape is completed.

**Comment by allenhwkim** [comment]
Did you include drawing library?

**Comment by allenhwkim** [comment]
I can reproduce the error.

**Comment by IAMtheIAM** [comment]
@allenhwkim Thank you! I can confirm this has fixed the error. The new code does not allow for selecting and deleting the markers now, not sure if that was your intention. Either way it is easy enough to change. :-)

**Comment by allenhwkim** [comment]
@IAMtheIAM hmm, it should allow select and deleting it. I might not have built and pushed.
