### ISSUE TITLE
How to hook marker on dragend event.

### ISSUE THREAD

**Issue by kharatps02** [ng2-ui/ng2-map#2]
Thanks for creating module for angular 2.0 support .

I want  to catch marker position ( lat,lon) on dragend event of it so how to hook that event .

**Comment by allenhwkim** [comment]
Thanks for using it. This should work.
`(markerDragEnd)="myFunc()"`

**Comment by allenhwkim** [comment]
it wasn't "drag_end", but "dragend". Fixed it. Please test

**Comment by kharatps02** [comment]
Thanks for reply ,
It is not working, dragend event is not calling .

 <ng2-map [center]="mapCenter" zoom="4">
        <marker [position]="mapCenter" [draggable]="true" (dragend)="clicked($event)"></marker>
 </ng2-map>


Error console ,

TypeError: Cannot read property 'open' of undefined
    at Ng2MapComponent.openInfoWindow (http://localhost:4200/vendor/ng2-map/dist/components/ng2-map.component.js:103:29)
    at HomeComponent.clicked (http://localhost:4200/app/home/home.component.js:35:33)

**Comment by allenhwkim** [comment]
At leaset It works with this plunker. I have updated plunker
http://plnkr.co/edit/9AI9dg?p=preview.

I think you want to call openInfoWindow when dragend. I have also tested with openInfoWindow which worked fine.

**Comment by kharatps02** [comment]
Thanks its working for me .
