### ISSUE TITLE
support AOT compiler

### ISSUE THREAD

**Issue by aitboudad** [ng2-ui/ng2-map#21]

**Comment by allenhwkim** [comment]
Could you explain the reason why need this?

**Comment by aitboudad** [comment]
Could you explain the reason why need this?

> the ng2-map doesn't support AoT compilation due to missing metadata.json files that need to be included with d.ts files. https://github.com/angular/angular/issues/11262#issuecomment-244472000

also see [Aot documentation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) for an introduction to this topic
