### ISSUE TITLE
Configure Google API key through Ng2MapeModule

### ISSUE THREAD

**Issue by aitboudad** [ng2-ui/ng2-map#30]
```ts
@NgModule({
  imports: [
    Ng2MapModule.forRoot({ apiUrl: '...' })
  ],
})
export class AppModule { }
```

**Comment by tcigrand** [comment]
+1

**Comment by staffanselander** [comment]
+1

What happens if there already is the api is already imported using normal script tag? 
Would be nice to be able to choose that as well. 
We are running hybrid version between angular 1 and angular 2. And have to import it using script tag.

**Comment by allenhwkim** [comment]
@staffanselander if `google.maps` is already there, this API does not insert any script tag into your document.

**Comment by staffanselander** [comment]
@allenhwkim That made my day! Thanks for quick reply
