### ISSUE TITLE
Webpack Debugging Issue With Typescript Source Code

### ISSUE THREAD

**Issue by allenhwkim** [ng2-ui/ng2-map#31]
It is very hard to debug with webpack, and I do not see any sourcemap from ts to js. All I see is '.js' files with webpack, which is not useful when we develop.

However, it's ok with systemjs. I had to put back `systemjs.config.js` and `debug.html` for proper debugging.

What am I missing webpack with typescript sourcemap?

**Comment by aitboudad** [comment]
it's work fine for me see bellow (chrome)

![webpack](https://cloud.githubusercontent.com/assets/1753742/20249254/707e528a-a9ed-11e6-87df-3ce77c7749c5.gif)

If you use `firefox` you should enable the source map https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Source_maps
