### ISSUE TITLE
Allow `[options]` for all attributes

### ISSUE THREAD

**Issue by allenhwkim** [ng2-ui/ng2-map#33]
* if [options] is given, all other inputs are ignored or error out.
* if [options] is changed, run `setOptions` to apply changes.

* The following object should apply these changes
  * ng2-map
  * circle
  * polygon
  * marker
  * info-window

**Comment by allenhwkim** [comment]
@aitboudad please yay or nay for this direction

**Comment by aitboudad** [comment]
:+1:
