### ISSUE TITLE
Lots of console.log calls

### ISSUE THREAD

**Issue by tcigrand** [ng2-ui/ng2-map#40]
I think the number of `console.log` calls should be cut down.

If there are `console.log` calls that should stay, I was thinking of a couple options and wanted to get your feedback on what you all thought was best for this project.

1. Check if angular is running in dev mode before logging to the console.
[It looks like this function could be used to do that.](https://github.com/angular/angular/blob/1b5384ee54d8faeb3222f312868f28d26d8d42e9/modules/%40angular/core/src/application_ref.ts#L60-L63)

2. Create a `dev` mode specific to this project and default it to false to hide them for the majority of users.

**Comment by allenhwkim** [comment]
Thanks

Can you make some detailed suggestions or PR?

**Comment by tcigrand** [comment]
Yes, likely not for a few days though.

**Comment by allenhwkim** [comment]
Just as a note
https://github.com/yahoo/strip-loader

**Comment by allenhwkim** [comment]
Release with 0.9.2, closing please verify the change.
