### ISSUE TITLE
Multiple maps in a single page shows the last map only

### ISSUE THREAD

**Issue by allenhwkim** [ng2-ui/ng2-map#5]

**Comment by uzumakinaruto123** [comment]
I am facing this issue ! Issue is closed , did miss something from documentation ? @allenhwkim  Thanks

**Comment by allenhwkim** [comment]
It seems working fine. Check this. Are you using old version?
https://rawgit.com/ng2-ui/ng2-map/master/app/index.html#/multiple-map

**Comment by uzumakinaruto123** [comment]
I am using the latest one. Installed it today itself. And , I checked that demo but its not working.

**HTML :** 

```
<ng2-map  zoom="13" center="CHUO-KU, TOKYO 103-0012 JAPAN"  scrollwheel="false">
      <marker position="CHUO-KU, TOKYO 103-0012 JAPAN" (click)="onMarkerClick($event)"></marker>
      <info-window id="iw">
        lat: [[lat]], lng: [[lng]]
      </info-window>
    </ng2-map>

<ng2-map  zoom="13" center="CHUO-KU, TOKYO 103-0012 JAPAN"  scrollwheel="false">
      <marker position="CHUO-KU, TOKYO 103-0012 JAPAN" (click)="onMarkerClick($event)"></marker>
      <info-window id="iw2">
        lat: [[lat]], lng: [[lng]]
      </info-window>
    </ng2-map>

<ng2-map  zoom="13" center="CHUO-KU, TOKYO 103-0012 JAPAN"  scrollwheel="false">
      <marker position="CHUO-KU, TOKYO 103-0012 JAPAN" (click)="onMarkerClick($event)"></marker>
      <info-window id="iw3">
        lat: [[lat]], lng: [[lng]]
      </info-window>
    </ng2-map>
```


**dependencies :**


```
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "^2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "@types/google-maps": "^3.2.0",
    "angular2": "^2.0.0-beta.21",
    "angularfire2": "2.0.0-beta.6",
    "firebase": "3.6.1",
    "ionic-angular": "^2.0.0-rc.5-201701131937",
    "ionic-native": "^2.2.16",
    "ionicons": "3.0.0",
    "ng2-map": "^0.14.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  }
```


Thanks !

**Comment by uzumakinaruto123** [comment]
@allenhwkim  Here is the plukr , reproducing the same issue  [PLUNKR](http://plnkr.co/edit/qMXwzA2kXpXxoLMU3iTR?p=preview)

**Comment by allenhwkim** [comment]
It's because of the racing condition of loading google maps API.
You can manually insert script tag in your html like the following.

https://plnkr.co/edit/B2jMxS93oGXZYVEmW6Py?p=preview

There is one bug on this approach, I will make a fix soon

**Comment by uzumakinaruto123** [comment]
That did work !  Can I know whats the bug ? just to be aware of . Thanks , appreciate your work ! 👍

**Comment by allenhwkim** [comment]
When `ng2-map` starts and google map API is not loaded, it loads google API by injecting `<script>` tag with a callback.
The callback function initialize the actual map, but only one map. That's why the last map only initializes.

To initialize all maps, the callback function needs to remember not only one but all map instance, and initializes it. However, I do not think it's worth  to try it. I welcome PR for this though.

**Comment by allenhwkim** [comment]
This has been fixed and released.
