### ISSUE TITLE
Error when using Places and Maps

### ISSUE THREAD

**Issue by Storchissimo** [ng2-ui/ng2-map#51]
I have a component where i use a map and a input-field for places.

<input type="text" id="store_address" class="form-control" places-auto-complete (initialized$)="initialized($event)" (place_changed)="placeChanged(place)">

<ng2-map [center]="addressForMap">
    <marker position="{{addressForMap}}"></marker>
</ng2-map>

If the places-input is before the map, the places-field is loaded, but not the map.
If the map is before the places-input, the map is loaded.

But in both cases I can not use both compinents

**Comment by allenhwkim** [comment]
Thanks for reporting it, but I don't understand your issue. 
Can you create a plunker example to illustrate your issue?

**Comment by FloPersus** [comment]
Hi,

I have the same problem,

Can you provide an example with this two features ? 

Thx

**Comment by zwtokio** [comment]
yo encontré una solución [https://github.com/ng2-ui/map/issues/94#issuecomment-282142516](comment issues)
