### ISSUE TITLE
map events not firing

### ISSUE THREAD

**Issue by spike83** [ng2-ui/ng2-map#53]
The events from map are not fired.
I guess because the L21 of services/ng2-map.ts has a bug. The eventName contains the prefix 'map_' but the events of gm are not named with this prefix.
When I change the name of e.g. 'map_click' to 'click' in debugger it works.

**Comment by allenhwkim** [comment]
Thanks for reporting it. I will make a fix soon

**Comment by spike83** [comment]
I found another problem. The provided value to the eventlistener of `this` is the map object. Better would be to provide the effective `event` object.
I added a pull request with this fix.

**Comment by allenhwkim** [comment]
I think this PR works for map, but not working with other map objects; marker, circle, etc.

`this` provides the object, so that user can access the map, marker, circle, ... etc
`event` provides the event itself, so that user can access latLng, etc
We need both. With Angular2, `this` is normally the component itself.

I will think about a better solution for map and other objects.

**Comment by spike83** [comment]
ok, we could do something like `emit(<InterfaceType>{object: this, event: event})`. Where InterfaceType makes clear what will be returned.
So the outputs could be defined as `new EventEmitter<InterfaceType>());`

**Comment by allenhwkim** [comment]
It's an idea, but I need to think about backward compatibility too. 
Currently it's passing an object, not an event. 

I am thinking of setting `event.target` by passing only one. not two.

**Comment by spike83** [comment]
I found another problem in this direction. When using the DataLayer the elements have not set ng2MapComponent. So InfoWindow example is not applicable when using DataLayer.
It would be great when the `event.target` could have `ng2MapComponent` set in all cases.

Should I enhance the pull request to provide the `event`, the `event.target` and `event.target.ng2MapComponent`?

**Comment by allenhwkim** [comment]
I think it's better to change DataLayer to have ng2MapComponent like any others.

https://github.com/ng2-ui/ng2-map/blob/master/src/directives/base-map-directive.ts#L55

Then. event.target should always have Ng2MapComponent already without setting it.

**Comment by spike83** [comment]
DataLayer itself has set the `ng2MapComponent` vial `BaseMapDirective` but on DataLayer you load geoJson data or add features which could fire events like drawing geometries. But these geometry object which would be `event.target` have not set the `ng2MapComponent`.
An option to capsule DataLayer could be to use the Events on DataLayer to set stuff otherwise set by `BaseMapDirective`.

**Comment by allenhwkim** [comment]
@spike83, I don't quite get what you are saying on the above. 
However, I will implement `event.target` first. I think implementation will satisfy almost all requirements of accessing an event object.

**Comment by spike83** [comment]
Thanks. It looks fine so far. But the initial problem on event names seems not to be solved (I've not tested yet but cannot see it in your change).
https://github.com/ng2-ui/ng2-map/pull/55/commits/f9e6a5919ef282a746eed18f3c1d31f0476f353d#diff-3bc567c5452e940654fad6f79697751eR20

**Comment by allenhwkim** [comment]
I don't know where you find `map_click`, which was the old implementation. We should use `click` now, However, it also fires DOM event that you can filter out.
```
if (event instanceof MouseEvent) {
   return false;
}
```

**Comment by allenhwkim** [comment]
added back events `mapClick` to avoid DOM events. related to issue #55
