### ISSUE TITLE
marker does not initialize when running with AoT

### ISSUE THREAD

**Issue by dweitz43** [ng2-ui/ng2-map#54]
Hi, I have been looking at this issue I have been experiencing for some time now, thinking it may have been a problem with my code, which is still very possible, but I thought I might reach out here for possible help/extra knowledge on the idea.

Everything works fine when running a normal development server inside a project created by the ng-cli. However it appears when running the server using AoT compilation, Marker elements do not get initialized correctly within components and therefore are not rendered properly on the app ui. The first screenshot below was taken when running my project with `ng serve,` it is possible to see in the console that a statement is logged by the base-map-directive.js when the Marker is initialized, and then I log the Marker object from within my map-modal component after subscribing to its initialized$ observable.

<img width="1280" alt="screen shot 2016-12-16 at 12 00 35 pm" src="https://cloud.githubusercontent.com/assets/12060437/21258788/47cf734c-c387-11e6-8cb5-45ef3f427b43.png">

However, when running the app using `ng serve --aot`, it is possible to see from the next screenshot that the initialization statement is never logged to the console by base-map-directive.js, and the statement logged from my component's subscription to the initialized$ observable is not logged as well:

<img width="1280" alt="screen shot 2016-12-16 at 12 05 58 pm" src="https://cloud.githubusercontent.com/assets/12060437/21258955/067b6e36-c388-11e6-85c6-c76766a8cc69.png">

I am not too sure why this could be happening, I thought that I understood the documentation and created the map and marker correctly, but I could have done something wrong.

The html template code for the map and marker:
```
<ng2-map zoom="15" [center]="location.location">
   <marker [position]="location.location" animation="DROP"></marker>
</ng2-map>
```

map-modal.component.ts:
```
@Input() location: {name: string, location: google.maps.LatLngLiteral};
@ViewChild(Ng2MapComponent) ng2Map: Ng2MapComponent;
@ViewChild(Marker) ng2Marker: Marker;
map: google.maps.Map;

....

  ngOnInit() {
    this.ng2Map.mapReady$.subscribe(map => {
      this.map = map;
      this.center = this.map.getCenter();
      google.maps.event.trigger(map, 'resize');
      this.map.setCenter(this.center);
      this.directionsService = new google.maps.DirectionsService();
      this.directionsDisplay = new google.maps.DirectionsRenderer({map});
      this.directionsDisplay.setPanel(this.document.getElementById('steps-panel'));
      this.initialized = true;
    });
    this.ng2Marker.initialized$.subscribe(marker => {
      console.log(marker);
    });
  };
```

any help or info would be greatly appreciated, i would really love to get this working with AoT, and the Marker on the map is definitely important to the user experience

**Comment by allenhwkim** [comment]
I could reproduce same issue with `ng serve --aot`. I have no idea why it's not running. I suspect it's angular-cli issue. anyway, help is appreciated for this.

**Comment by allenhwkim** [comment]
@aitboudad Could you verify this, and make it closed?

**Comment by uzumakinaruto123** [comment]
I am using ng2-map in ionic 2 , It was building until 0.15.1 version was installed

But , I was facing marker issue so I tried 0.15.2 , now app does not build ...
```

> ionic-app-scripts build --prod

[01:47:06]  ionic-app-scripts 1.0.1
[01:47:06]  build prod started ...
[01:47:06]  preprocess started ...
[01:47:06]  preprocess finished in 7 ms
[01:47:06]  clean started ...
[01:47:06]  clean finished in 9 ms
[01:47:06]  copy started ...
[01:47:06]  ngc started ...
can't resolve module ./components/custom-marker from C:/xampp/htdocs/ionic2/Fx/FxLookUp2/node_modules/ng2-map/dist/ng2-map.module.d.ts
[01:47:15]  build prod failed: Cannot read property 'CustomMarker' of undefined, resolving symbol Ng2MapModule in
            C:/xampp/htdocs/ionic2/Fx/FxLookUp2/node_modules/ng2-map/dist/ng2-map.module.d.ts, resolving symbol
            Ng2MapModule in C:/xampp/htdocs/ionic2/Fx/FxLookUp2/node_modules/ng2-map/dist/ng2-map.module.d.ts
[01:47:15]  ionic-app-script task: "build"

```


Dependencies :- 

```
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "^2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "@types/google-maps": "^3.2.0",
    "angular2": "^2.0.0-beta.21",
    "angularfire2": "2.0.0-beta.6",
    "firebase": "3.6.1",
    "ionic-angular": "^2.0.0-rc.4",
    "ionic-image-loader": "^1.3.0",
    "ionic-native": "^2.2.16",
    "ionicons": "3.0.0",
    "ng2-img-fallback": "^0.2.1",
    "ng2-map": "^0.15.2",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.0.1",
    "typescript": "2.0.9"
  }
```


Thanks !

**Comment by allenhwkim** [comment]
@uzumakinaruto123 
It works for me with ngc. 
Please create a different issue with your source code and configs.

**Comment by uzumakinaruto123** [comment]
Ok . Here it is #85 👍

**Comment by aitboudad** [comment]
@dweitz43 can you provide us a repo with the changes to reproduce your issue?
