### ISSUE TITLE
Circle, polygon directives break SVG template rendering

### ISSUE THREAD

**Issue by lrodziewicz** [ng2-ui/ng2-map#57]
If you happen to use SVG into one of your other components it won't work.

Suggestion: ng2-map directives should be renamed to not collide with the SVG reserved elements.

**Comment by allenhwkim** [comment]
Are you sure about this? Circle and polygon are only works within Ng2-map

**Comment by allenhwkim** [comment]
Please verify this, or else, it will be closed soon

**Comment by lrodziewicz** [comment]
It's been holidays, I haven't really have time to replay.

I'm sure that it's not working just try to use component like:
`
import {Component} from '@angular/core';

@Component({
  selector: 'svg-element',
  styles: [``],
  template: `
    <svg height="230px" width="230px" viewBox="0 0 120 120">
       <circle cx="60" cy="60" r="60" fill="red"/>
    </svg>
  `
})
export class SvgComponent {
}
`
Theoretically selector for `circle` directive is `ng2-map>circle` but something is not working as expected. It might be a bug in ng2. For now I created my own module that include all parts expect problematic directive and I'm using it instead of one provided by ng2-map.

**Comment by allenhwkim** [comment]
It seems that `ng2-map > circle` does not work with angular2. It applies to `circle` all the time.
It could be ng2 bug, but not sure about it.

Meanwhile please use `ng2NonBindable` in `svg` tag to make it work
https://plnkr.co/edit/XMqUL7cpKcv2Vzs7ArRa?p=preview

**Comment by allenhwkim** [comment]
This has been implemented. Please use `map-circle` and `map-polygon` when conflicts to `svg`
