### ISSUE TITLE
Using NG2 library show all console logs in the console. 

### ISSUE THREAD

**Issue by brasycad** [ng2-ui/ng2-map#58]
Using NG2 library show all console logs in console. 
How I can disable this console.log for production mode?

Thanks in advance!

**Comment by allenhwkim** [comment]
This should be already handled if you use .umd.js. webpack suppress all console.log when it is build for production.

https://github.com/ng2-ui/ng2-map/blob/master/package.json#L15

https://github.com/ng2-ui/ng2-map/blob/master/webpack.config.js#L37

**Comment by allenhwkim** [comment]
please verify the answer, or else, it will be closed soon

**Comment by allenhwkim** [comment]
Closing for no answer
