### ISSUE TITLE
DrawingManager Access

### ISSUE THREAD

**Issue by thorcode** [ng2-ui/ng2-map#60]
I have integrated your code into my app and it is working quite well.  I certainly appreciate your time and isntructions.

I am new to ng2 and TypeScript and my use case requires that I utilize the DrawingManager.  

I have most of the DrawingMgr features I am looking for working in a simple html page and js but wanted to bring it into my ng2 app.  Do you any code examples or snippets on how to 'instantiate' a DrawingManager and use it to subscribe the manager's events within your module?

e.g. ->

`drawingManager = new google.maps.drawing.DrawingManager({
          drawingMode: null,
          drawingControl: false, 
          drawingControlOptions: {
            position: google.maps.ControlPosition.BOTTOM_CENTER,
            drawingModes: ['marker', 'circle', 'polygon', 'polyline', 'rectangle']
          },
          markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
    	});
    	drawingManager.setMap(map);`

and

`google.maps.event.addListener(drawingManager, 'polygoncomplete', function(poly) {
		 	drawingManager.setDrawingMode(null);
  			poly.setEditable(true);
  			poly.setDraggable(true);
  			poly.addListener("dragend", polygonDragged);
  			google.maps.event.addListener(poly.getPath(), "insert_at", polygonPathChanged);
  			google.maps.event.addListener(poly.getPath(), "remove_at", polygonPathChanged);
  			google.maps.event.addListener(poly.getPath(), "set_at", polygonPathChanged);
  			describePolygon(poly);
		});`

Thanks, in advance, for your time.

John 
ps - sorry if the issues page was not the correct place to ask this question - please advise

**Comment by allenhwkim** [comment]
It's better to make a simple directive for this feature. Let me see how long it takes.

**Comment by allenhwkim** [comment]
This is released with 0.13.0, please test

**Comment by thorcode** [comment]
Thanks for the prompt and awesome response.  I will check it out and let you know.

John

**Comment by thorcode** [comment]
After a little reading and trial and error I have the basics working...  thanks a bunch - great job!

**Comment by sanjaykumarns** [comment]
I am using ng2-map version: 0.15.7, But while including drawing-manager, it is telling DrawingManager of undefined like below:

Uncaught TypeError: Cannot read property 'DrawingManager' of undefined
    at DrawingManager.BaseMapDirective.initialize (VM2113 ng2-map.umd.js:319)
    at eval (VM2113 ng2-map.umd.js:308)
    at SafeSubscriber.schedulerFn [as _next] (VM2114 core.umd.js:3701)
    at SafeSubscriber.__tryOrUnsub (VM2123 Subscriber.js:234)
    at SafeSubscriber.next (VM2123 Subscriber.js:183)
    at Subscriber._next (VM2123 Subscriber.js:125)
    at Subscriber.next (VM2123 Subscriber.js:89)
    at EventEmitter.Subject.next (VM2120 Subject.js:55)
    at EventEmitter.emit (VM2114 core.umd.js:3675)
    at sg.eval (VM2113 ng2-map.umd.js:198).


Can you try including the following code in plunker: https://plnkr.co/edit/6e1qWK?p=preview

 <drawing-manager
      [drawingMode]="'marker'"
      [drawingControl]="true"
      [drawingControlOptions]="{
        position: 2,
        drawingModes: ['marker', 'circle', 'polygon', 'polyline', 'rectangle']
       }"
      [circleOptions]="{
        fillColor: '#ffff00',
        fillOpacity: 1,
        strokeWeight: 5,
        editable: true,
        zIndex: 1
      }"></drawing-manager>

**Comment by allenhwkim** [comment]
```
//noinspection TypeScriptCheckImport
import { Ng2MapModule } from 'ng2-map';
@NgModule({
  imports: [
    BrowserModule, 
    FormsModule, 
    ReactiveFormsModule, 
    Ng2MapModule.forRoot({
      apiUrl: 'https://maps.google.com/maps/api/js?libraries=visualization,places,drawing'
    })
  ],
  declarations: [AppComponent],
  bootstrap: [ AppComponent ]
})
export class AppModule {}
```
Drawing library is required to use Drawing Manager according to google.
https://developers.google.com/maps/documentation/javascript/drawinglayer.
