### ISSUE TITLE
how to access polygon point value(latitude and longitude )

### ISSUE THREAD

**Issue by AsankaD7** [ng2-ui/ng2-map#62]
I use ng2-map polygon example.I want to draw shape file using this example I want to access every polygon point values(latitude and longitude) like a ng2-map info-window example.How can I do that? 

Thanks.

**Comment by allenhwkim** [comment]
1. get polygon object as described in README.md
2. call `getPaths()` for all lat/lng of your polygon.

https://developers.google.com/maps/documentation/javascript/3.exp/reference#Polygon

**Comment by mihirkadve** [comment]
not able to get paths of clicked polygon on polygon click,
 getting value of first polygon on whichever polygon i click .

Please Help.
