### ISSUE TITLE
panel is not working

### ISSUE THREAD

**Issue by Avinash-Gupta-B** [ng2-ui/ng2-map#66]
Unable to append directionsResult to the panel.

[https://rawgit.com/ng2-ui/ng2-map/master/app/index.html#/directions-renderer]()

<ng2-map [hidden]="!checked" zoom="13" [center]="origin">
    <marker *ngFor="let pos of positions" [position]="pos"></marker>
    <directions-renderer
      [suppressMarkers]="true"
      [draggable]="true"      
      (directions_changed)="directionsChanged()"
      [directions-request]="direction"
      [panel]="directions-panel">
   `</directions-renderer>`
`  </ng2-map>`
  <button (click)="positions = showRandomMarkers()">Show Random Markers</button>
  <button (click)="positions = showDirection()">ShowDirections Markers</button>
   `<br/>`
  ` <div [hidden]="!checked" id="directions-panel" style="width: 28%; float:left; height: 450px; overflow: auto; padding: 0px 5px"></div>`

If possible please provide any plunker example with panel using direction renderer.

**Comment by allenhwkim** [comment]
The problem is that the value of [panel] must be a Node, not a string.
You can achieve that by setting panel separately like the following

```
  ngOnInit() {
    this.directionsRendererDirective['initialized$'].subscribe( directionsRenderer => {
      this.directionsRenderer = directionsRenderer;
      this.directionsRenderer.setPanel(document.querySelector('#my-panel'));
    });
  }
```

**Comment by Avinash-Gupta-B** [comment]
ya i solved the issue by setting setPanel method in directions-renderer.ts file, But the way you solved the issue is very generic and nice.
Thank you very much for response.

**Comment by Avinash-Gupta-B** [comment]
How can we create a way points from one base origin to multiple destination points @allenhwkim

**Comment by allenhwkim** [comment]
@Avinash-Gupta-B out of scope. That question should be asked to Google Maps API group, not to me. Please use stackoverflow for it.
