### ISSUE TITLE
Cannot use Google charts with ng2-map

### ISSUE THREAD

**Issue by matvey-kazakov** [ng2-ui/ng2-map#68]
there are several checks for google, not google.maps (I've found 3)
https://github.com/ng2-ui/ng2-map/blob/master/src/components/ng2-map.component.ts#L76
https://github.com/ng2-ui/ng2-map/blob/master/src/components/ng2-map.component.ts#L101
https://github.com/ng2-ui/ng2-map/blob/master/src/directives/places-auto-complete.ts#L25

Because of that if I load google charts api
`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>`
ng2-map is not properly initialized and throws exceptions. When I've fixed those, it worked for me.

**Comment by allenhwkim** [comment]
Thanks. I only thought of google maps, not with other apis.
Can you make a pull request?

**Comment by matvey-kazakov** [comment]
I've created it, but I'm not sure why `ngc` generates different code for `dist/components/*` than in repository. If you advice I can rebuild pull request with smaller number of file changes.

**Comment by allenhwkim** [comment]
This has been merged and fixed.
