### ISSUE TITLE
Feature Request : Fallback position option if position fails.

### ISSUE THREAD

**Issue by uzumakinaruto123** [ng2-ui/ng2-map#73]
I am using address to center map and center the marker position.

But , some addresses won't load , resulting in a runtime error. where **map won't load**. It would help if there's a **fallback position property** which will load if actual one fails. 

For example , the following location will fail and map won't load. having property like [fallback]="**someObviousLocation**" will help.

```
<ng2-map style="border:1px solid black;width:50%;height:20vh" zoom="13" center="41 WEST PUTNAM AVE. THIRD FLOOR GREENWICH, CT 06830 U.S.A" scrollwheel="false">
    <marker position="41 WEST PUTNAM AVE. THIRD FLOOR GREENWICH, CT 06830 U.S.A" (click)="onMarkerClick($event)"></marker>
  </ng2-map>
```

Thanks !

**Comment by allenhwkim** [comment]
Thanks for reporting this. This will be implemented

**Comment by allenhwkim** [comment]
use `geoFallbackCenter` or `geoFallbackPosition`

**Comment by uzumakinaruto123** [comment]
@allenhwkim  Fallback only accepting LatLng literals. If address string is passed it throws error `InvalidValueError: setPosition: not a LatLng or LatLngLiteral: not an Object` .  I intend to pass only city name if actual position fails. but it does not work. Thanks

**Comment by allenhwkim** [comment]
That's intentional. fallback option must be lat/lng. What if the current position is not available by browser? What if geocode always fails? It's better to be safe to have Lat/Lng instead of string.

**Comment by uzumakinaruto123** [comment]
I do understand that.  Hence , the fallback is just going to be the city name(which is ok for my use case). which won't fail 95% of the times.  

Point of not using LatLng in actual position is unavailability of LatLng data. If LatLng data was present , it won't even fail in most cases , so fallback won't be required .

Fallback will mostly be used where address string are passed as positions.
