### ISSUE TITLE
Custom markers do not stay in position when zooming in and out

### ISSUE THREAD

**Issue by Mercality** [ng2-ui/ng2-map#75]
Custom markers won't stay on their corresponding location when zooming in and out i can see the setposition function is called when the map is zoomed in and out but for some reasons the markers all end in wrong locations.

EDIT: Just noticed that this happens when using the string format for position eg: '80.25, -65.23'. Using the array format eg: [80.25, -65.23] doest not trigger any strange behaviour when zooming in and out.

**Comment by allenhwkim** [comment]
@ro- Can you take a look into it if possible?

**Comment by ro-** [comment]
@allenhwkim I've only used the array format to be honest. The interpreted the string input for use in geocoding. 

Will have a look.

**Comment by allenhwkim** [comment]
Tested with this code, and it all works fine for me
```
  <ng2-map center="42.99,-77.79">
    <custom-marker position="42.99,-77.79">
      <div><b>Hi, USA</b>
        <img src="http://icons.iconarchive.com/icons/custom-icon-design/2014-world-cup-flags/32/USA-icon.png" />


      </div>
    </custom-marker>
    <marker position="42.99,-77.79"></marker>
  </ng2-map>
```
![image](https://cloud.githubusercontent.com/assets/1437734/22856833/ca06530a-f067-11e6-93bd-35b25353de28.png)

**Comment by allenhwkim** [comment]
FYI, when you specify a lat/lng as string, you should use `lat, lng` format.

Not this one
 <strike>`[center]="[42.99,-77.79]"`</strike>
Nor, this one
 <strike>`center="[42.99,-77.79]"`</strike>

Only this format is accepted for proper parsing from string
  `center="42.99,-77.79"`

Or, you can use geo-coding   
  `center="Brampton, Canada"`
