### ISSUE TITLE
eval security risks 

### ISSUE THREAD

**Issue by nm-saravanan** [ng2-ui/ng2-map#80]
I am getting the eval issue form services/option-builder.js
rollup: Use of `eval`is strongly discouraged, as it poses security risks and may cause issues with minification.

**Comment by allenhwkim** [comment]
I and we all know eval is not encouraged to use.

https://github.com/ng2-ui/ng2-map/blob/master/src/services/option-builder.ts#L136

```
    if (input.match(/^[A-Z][a-zA-Z0-9]+\(.*\)$/)) {
      try {
        let exp = 'new google.maps.' + input;
        // tslint:disable-next-line
        output = eval(exp);
      } catch (e) {}
    }
```

I will try again without using eval.
Thanks for reporting it.

**Comment by aitboudad** [comment]
@allenhwkim I'm on it

**Comment by allenhwkim** [comment]
thanks @aitboudad

**Comment by allenhwkim** [comment]
@aitboudad try test with this, the most complicated cast I can think of.

```
<ng2-map 
  center="[40.6892,-74.0444]" zoom="18"
  map-type-id="MapTypeId.SATELLITE" tilt="45"
  street-view="StreetViewPanorama(document.querySelector('div#sv'), {position:new google.maps.LatLng(40.688738,-74.043871)})">
</ng2-map>
<div id="sv" />
```

**Comment by aitboudad** [comment]
@allenhwkim couldn't find a better so I leave it for you ;),

not sure if we should support this feature, I would vote to remove it at all

**Comment by allenhwkim** [comment]
@aitboudad without this, users need to have `google.maps` on their app level, which most of them don't.

For example, 

`google.maps` can only be required when they are using `ng2-map`, however if we make this as configured as a variable, they need to set `new google.maps.StreetViewPanorama.........`, which will fail without having google api installed with `<script>` tag.
