### ISSUE TITLE
Upgrade webpack from 1.* to 2.*

### ISSUE THREAD

**Issue by allenhwkim** [ng2-ui/ng2-map#84]
Webpack version 2 has very significant changes, and configuration is not backward compatible
https://blog.madewithenvy.com/getting-started-with-webpack-2-ed2b86c68783#.3tv0tylgk

We need to upgrade to webpack 2.* and rebuild our webpack.config.js

**Comment by aitboudad** [comment]
see #88

**Comment by allenhwkim** [comment]
@aitboudad thanks
