### ISSUE TITLE
How get access to google.map object?

### ISSUE THREAD

**Issue by ziXet** [ng2-ui/ng2-map#86]
For some low-level operations such as event.trigger, I need to have access to the google.map object. Is there anyway to get this object?

**Comment by allenhwkim** [comment]
It's on README.md
![Uploading image.png…]()

**Comment by ziXet** [comment]
I think what I get from onMapReady is the map instance. Not the actual "google.maps" object.
For example creating a LatLng object. There only way to access to the LatLng class is though the "google.maps" object. correct me if I'm wrong.

Thanks

**Comment by yossely** [comment]
Hi @ziXet could you access the `google.maps` object? I also need it to fit bounds of the map
