### ISSUE TITLE
starting with version 1.5.2 does not work with latest angular/angular-cli/typescript

### ISSUE THREAD

**Issue by ujibang** [ng2-ui/ng2-map#87]
the new configuration method via `Ng2MapModule.forRoot()` does not work with latest versions of angular/angular-cli/typescript (not sure which one causes the problem).

I recently updated my project with latest packages and ng2-map to 1.5.3

Config ng2-map in app.module imports array lead to compilation failure (Error encountered resolving symbol values statically)

I also tried invoking `Ng2MapModule.forRoot({apiUrl:....})` somewhere else with no success. In the console I have

```
Ng2MapModule config # where I can read the correct key qparam
...
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
```

**Steps to reproduce and a minimal demo**

install

angular version 2.3.1
angular/cli version 1.0.0-beta.31
typescript version 2.1.6

try to compile

`ng b`

the only *workaround* was downgrading to 1.5.1 and use `Ng2MapComponent['apiUrl'] = 'https://maps.google.com/maps/api/js?key=...'`

**Comment by aitboudad** [comment]
the latest version of `angular` is v2.4.7, please update it and try again

**Comment by allenhwkim** [comment]
@aitboudad According to http://angularjs.blogspot.ca/2016/08/angular-2-rc5-ngmodules-lazy-loading.html, forRoot is introduced at RC5.
@ujibang Could you provide your full AppModule.js, package.json here?

**Comment by aitboudad** [comment]
some of angular version has some known issue with ngc itself and depend on which version we use during compilation of `ng2-map`, so it is preferable to use the latest one

**Comment by tacree** [comment]
I think this may be a problem with CLI.  I am having the same problem when using angular-cli, but if I run the examples from the NG2-Map project using straight webpack, they works fine.  See these 2 issues in the angular-cli project:

https://github.com/angular/angular-cli/issues/3674
https://github.com/angular/angular-cli/issues/4647

**Comment by tacree** [comment]
I updated to the latest version of angular-cli and it resolved this issue.  I updated from beta.30 to beta.31 and compilation started working.  Here is my version info:

@angular/cli: 1.0.0-beta.31
node: 7.4.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

**Comment by ujibang** [comment]
@tacree are you sure that building from angular-cli and straight from webpack uses the same version of typescript?

**Comment by tacree** [comment]
I updated angular-cli's version to beta.31 this morning and the problem still persists.  @ujibang the Typescript version being used by angular-cli is 2.0.10, which looks to be the same as what ng2-map is using. 

FWIW, removing the lazy configuration with the static method call to "forRoot" and going back to configuring the Ng2MapComponent.apiUrl property resolves the problem, however, this is not a desirable solution.

**Comment by ujibang** [comment]
my package.json

```
...
  "dependencies": {
    "@angular/common": "2.4.7",
    "@angular/compiler": "2.4.7",
    "@angular/compiler-cli": "2.4.7",
    "@angular/core": "2.4.7",
    "@angular/forms": "2.4.7",
    "@angular/http": "2.4.7",
    "@angular/platform-browser": "2.4.7",
    "@angular/platform-browser-dynamic": "2.4.7",
    "@angular/material": "2.0.0-beta.1",
    "@angular/router": "3.4.7",
    "@types/geojson": "1.0.0",
    "@types/google-maps": "^3.2.0",
    "@types/markerclustererplus": "^2.1.28",
    "ng2-map": "0.15.1"
  },
  "devDependencies": {
    ....
    "@angular/cli": "^1.0.0-beta.31",
    "typescript": "2.1.6",
    "webpack": "^2.2.1"
  }
}

```

**Comment by allenhwkim** [comment]
@ujibang your app module?

**Comment by ujibang** [comment]
pasting here the relevant part of app.module (@NgModule imports array)

```
imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    MaterialModule.forRoot(),
    NgReduxModule,
    Ng2MapModule,
    // need ng2-map 1.5.3 but bug https://github.com/ng2-ui/ng2-map/issues/87
    // Ng2MapModule.forRoot({ apiUrl: `https://maps.google.com/maps/api/js?key=${GMAPS_API_KEY}` });
    MyDateRangePickerModule,
    RlTagInputModule,
    HttpInterceptorModule,
    ...
  ],
```

**Comment by aitboudad** [comment]
seems related to `https://maps.google.com/maps/api/js?key=${GMAPS_API_KEY}`, if you put a string value it should work

**Comment by aitboudad** [comment]
@ujibang can you try with:
```ts
export class NgMapConfig {
    apiUrl = `https://maps.google.com/maps/api/js?key=${GMAPS_API_KEY}`;
}

@NgModule({
    imports: [
        ...
        Ng2MapModule.forRoot(NgMapConfig),
    ],
})
```

**Comment by ujibang** [comment]
still getting error

```
ERROR in Error encountered resolving symbol values statically. Calling function 'Ng2MapModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/uji/development/art/art-web-editor/src/app/app.module.ts, resolving symbol AppModule in /Users/uji/development/art/art-web-editor/src/app/app.module.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/uji/development/art/art-web-editor/src'
 @ ./src/main.ts 6:0-74
 @ multi ./src/main.ts
```

**Comment by allenhwkim** [comment]
@ujibang Do you have a Google Maps API Key?

**Comment by macropp** [comment]
Hi, I'm also getting the same error @ujibang is mentioning.

Versions I have:
angular-cli: 1.0.0-beta.26
node: 6.8.0
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

**Comment by aitboudad** [comment]
ok I'll try to provide you a working example with the latest `angular-cli` as it's work for me

**Comment by ujibang** [comment]
of course. ng-map 1.5.1 works very well. starting 1.5.2 I have that compilation error, i.e. the project does not build with `ng b` nor it works with `ng s`

**Comment by aitboudad** [comment]
I can reproduce it, working on a fix!

**Comment by aitboudad** [comment]
please try with `0.15.5` version

**Comment by aitboudad** [comment]
angular-cli repo: https://github.com/aitboudad/ng-cli-ng2-map

**Comment by allenhwkim** [comment]
@aitboudad thank you

**Comment by ujibang** [comment]
I confirm 0.15.5 fixes this issue, @aitboudad thank you

FYI, in order to parametrize the configuration I had to specify my api key this way:

in my conf.ts file

```
export const NgMapConfig = { apiUrl: 'https://maps.google.com/maps/api/js?key=<my-api-key>' };
```

in app.module.ts

```
import { NgMapConfig } from './conf'
...
imports. [
  ....,
  Ng2MapModule.forRoot(NgMapConfig),
  ...
]
```

**Comment by iamchriswick** [comment]
Any solution to this?

severity: 'Error'
message: ''ngui-map' is not a known element:
1. If 'ngui-map' is an Angular component, then verify that it is part of this module.
2. If 'ngui-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
at: '1,1'
source: 'Angular'
code: 'undefined'

**Comment by aitboudad** [comment]
ensure `Ng2MapModule` is imported in the module that your component is part of it.
