### ISSUE TITLE
How to create dynamically a InfoWindow?

### ISSUE THREAD

**Issue by ajcRodrigues** [ng2-ui/ng2-map#90]
I receive from server a couple of path (or routes) and dynamically show it on map as polyline. Now, I need to add a click event from a polyline and show up some informations of it.

Please, how can I do this?

**Comment by allenhwkim** [comment]
You are not encouraged to make the same multiple or dynamic info window.

    @Component({
      selector: 'ng2-map > info-window',
      inputs: INPUTS,
      outputs: OUTPUTS,
      template: `<ng-content></ng-content>`,
    })

As you see in the code, all htmls are angular HTML.

Within HTML, you can make it dynamic.

**Comment by allenhwkim** [comment]
Please also take a look info window example and make an example from it

This will be closed since there is no example provided to reproduce your issue.
