### ISSUE TITLE
Both Map and Auto-complete shows empty map.

### ISSUE THREAD

**Issue by eirikant** [ng2-ui/ng2-map#92]
By having both a autocomplete input and a <ng2-map></ng2-map> makes the map render white with no information. Or if the <ng2-map> comes first in the HTML the map works but auto-complete does not.

Having just the API url in the NgModel makes the auto-complete return the error:
`GET https://maps.google.com/maps/api/js&callback=initializePlacesAutoComplete `
By adding the API url to the component with
`Ng2MapComponent['apiUrl'] = 'https://maps.google.com/maps/api/js?key=KEY&libraries=visualization,places';`
the auto-complete will work, but the map will be white. 

Plunker with auto complete working but not map (because auto-complete is first in the HTML template)
https://plnkr.co/edit/UNSsES1NUxQ4xe80FMSD?p=preview

Plunkr with map working but auto-complete not because map is first in the HTML template
https://plnkr.co/edit/AG15WKcY62MxrAzGNq5t?p=preview

**Comment by eirikant** [comment]
The fix for #91 my ref the google api in the HTML file works around this too, but should probably be looked into!

**Comment by allenhwkim** [comment]
The same issue with #91. By pre-loading Google Maps API, you can resolve this issue.

https://plnkr.co/edit/oIff6S?p=preview

https://plnkr.co/edit/AG15WKcY62MxrAzGNq5t?p=preview

**Comment by allenhwkim** [comment]
This has been fixed and released as 0.15.7
