### ISSUE TITLE
return the place object for event 'place_changed' of PlacesAutoComplete

### ISSUE THREAD

**Issue by xiaohuiz** [ng2-ui/ng2-map#94]
Currently PlacesAutoComplete has an event of place_changed but no data include in the event, end user had to bind the initialized event to get the google.maps.places.Autocomplete object and call getPlace() in place_changed event handler. 

suggest change line 44 of "src/directives/places-auto-complete.ts" to the following line to include the place in the event itself

    this.autocomplete.addListener('place_changed', place => this.place_changed.emit(this.autocomplete.getPlace()));

**Comment by allenhwkim** [comment]
place_changed does not have argument according to this.
https://developers.google.com/maps/documentation/javascript/3.exp/reference#AutocompleteOptions

`this.getPlace()` is an option, but`this` scope is tricky. 

Although this module strictly follow the Google Maps API v3, we can think of an exception

**Comment by xiaohuiz** [comment]
current implementation of initialized event does not work if I add google map api script in my index.html. I guess it is because the event is emitted in the class constructor and angular 2 has not got an opportunity bind the event to my handler.

Since the only reason of bind this initialized event in my app is to get the autocomplete object to be used later to get the changed place, why not emit the place directly in the place_changed event.

**Comment by allenhwkim** [comment]
This has been fixed and released as 0.15.7
