### ISSUE TITLE
Custom markers are not attached to position

### ISSUE THREAD

**Issue by g-schmitz** [ng2-ui/ng2-map#95]
When the map is zoomed in or out, custom markers are not staying at their defined position.
While it seems like they would've been positioned absolute, they are sometimes thrown all over the place randomly on each zoom level.

Plunker example: https://plnkr.co/edit/XWoQ066YXjE3eKkwjlan?p=preview

**Comment by allenhwkim** [comment]
@g-schmitz thanks for reporting this
this has been fixed and released 0.15.6
