### ISSUE TITLE
Markers appears in DOM inspector but doesn't show in the map

### ISSUE THREAD

**Issue by martinmanzo** [ng2-ui/ng2-map#99]
I'm using a map with a heatmap and need to handle clicks on some parts of the map.
The heatmap shows ok. The problem comes when I generate the markers.

This is the code on the HTML:
```
<ng2-map (mapReady$)="onHeatMapReady($event)" zoom="5" center="-34.897585, -56.116454" mapTypeId="MapTypeId.ROADMAP">
    <heatmap-layer dissipating="true" radius="25"></heatmap-layer>
    <marker *ngFor="let p of mapMarkers" [position]="p"></marker>
</ng2-map>
```
This is how I add coordinates to the array:
```
this.mapMarkers = [];
for (let r of this.data['markers']) {
    this.mapMarkers.push(r);
}
```
`r` is an array with two elements. For example: ` [-34.890718, -56.084513]`
This produces the next HTML:
![image](https://cloud.githubusercontent.com/assets/3625887/23565266/9d6846c2-002b-11e7-9ce6-a44c295b3fbd.png)
But no marker is rendered on the map.

On the other hand if I do this:
```
<marker *ngFor="let p of  [[-34.890718, -56.084513], [-34.891029, -56.054405], [-34.89622, -56.104431]]" [position]="p"></marker>
```
I get the markers to render correctly.

Any clue of what I can be missing?

**Comment by allenhwkim** [comment]
It works fine with me.
https://plnkr.co/edit/6e1qWK?p=preview

You might need to run change detection, but I am not sure.  Please create your plunker example, so that I can debug for you.

**Comment by martinmanzo** [comment]
Yesterday I tried recreating the bug in plunker with no luck.
I could now.

https://plnkr.co/edit/t83FXjvp5k3dZHNwioMc?p=preview

As you can see the markers appears in the DOM but they don't get rendered.

**Comment by allenhwkim** [comment]
@martinmanzo Thanks for making the example.
It's strange that marker is not initialized when itself is newly created for your case.
I also found another bug when you look into your issue.

I will get back to you when I make an effort on my end.

**Comment by martinmanzo** [comment]
@allenhwkim sure thank you! Let me know if I can help you with this.

**Comment by allenhwkim** [comment]
Fixed, please verify

**Comment by martinmanzo** [comment]
@allenhwkim it's working! Awesome work, thanks!
